### ISSUE TITLE
Feature request: Add a status entity (e.g. binary_sensor) to allow automatic integration reload

### ISSUE THREAD

**Issue by fx-host-assistant** [AlexxIT/Dataplicity#39]
Hi,
Sometimes the tunnel stops working until Home Assistant is restarted. Since the Dataplicity integration currently doesn’t expose any entity, it’s not possible to detect this failure from within Home Assistant.

A simple binary_sensor reflecting the tunnel status (on = connected, off or unavailable = disconnected) would allow users to automate recovery. For example, if the sensor stays off or unavailable for 15 minutes, an automation could call homeassistant.reload_config_entry for that entity causing Dataplicity integration to reload and, hopefully, restoring the tunnel without restarting Home Assistant.

This would improve reliability and make failure recovery seamless.

Thank you for considering it

**Comment by ivano85** [comment]
What about a keepalive? Or heartbit?

**Comment by fx-host-assistant** [comment]
you can use an external system to monitor, e.g. uptimerobot, but it is something you have to add. Doing it internaly with an exposed entity, makes things more easy.

**Comment by riddik14** [comment]
same problem for me

**Comment by yarmak72** [comment]
Yep, it will be very helpful feature

**Comment by ivano85** [comment]
I've temporarily applied a workaround:

in configuration.yaml:
```yaml
binary_sensor:
  - platform: rest
    name: Reachable through Dataplicity
    resource: https://<your-public-name>.dataplicity.io
    method: GET
    timeout: 10
    value_template: "{{ not 'Device not Connected' in value }}"
    scan_interval: 60
```

Then, an automation to reload the integration (easier if you build it through the UI):
```yaml
alias: Reload Dataplicity
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.reachable_through_dataplicity
    from: null
    to: "off"
  - trigger: state
    entity_id:
      - binary_sensor.reachable_through_dataplicity
    from: null
    to: unavailable
    for:
      hours: 0
      minutes: 10
      seconds: 0
conditions: []
actions:
  - action: homeassistant.reload_config_entry
    metadata: {}
    data:
      entry_id: <entry id of Dataplicity integration>
mode: single
```

You can skip the unavailability check.

I think a similar periodic check could be included in the integration code at least.
